DROP DATABASE IF EXISTS Satlite;

CREATE DATABASE Satlite;

USE Satlite;

CREATE TABLE users (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(50),
    email VARCHAR(50),
    password VARCHAR(50)
);